apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: adaptto-2018-example
    ver: 1.0.0-SNAPSHOT
  name: adaptto-2018-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adaptto-2018-example
  template:
    metadata:
      labels:
        app: adaptto-2018-example
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: dulvac/osgi.example.kubernetes
        name: adaptto-2018-example
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /systemready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /systemalive
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adaptto-2018-example
  name: adaptto-2018-example
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30215
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adaptto-2018-example
  type: LoadBalancer
