apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example-systemready
    ver: 1.0.0-SNAPSHOT
  name: example-systemready
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-systemready
      valid: valid
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: example-systemready
        valid: valid
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: DOCKER_USERNAME/example.systemready
        name: example-systemready
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /system/health/ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /system/health/alive
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-systemready
  name: example-systemready
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-systemready
  type: LoadBalancer
