apiVersion: v1
kind: Service
metadata:
  name: {{ template "adapt-to-2018.fullname" . }}
  labels:
    app: {{ template "adapt-to-2018.name" . }}
    chart: {{ template "adapt-to-2018.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "adapt-to-2018.name" . }}
    release: {{ .Release.Name }}
